import pygame
from enum import IntEnum

#Tiles not pixels
M_WIDTH = 28
M_HEIGHT = 31
TEMP_WIDTH = 800
TILE_WIDTH = 124
WIN = pygame.display.set_mode((TEMP_WIDTH,TEMP_WIDTH))
pygame.display.set_caption("packer test 1")

BLUE     = (  0,   0, 255)
BLACK    = (  0,   0,   0)
SALMON   = (250, 128, 114)
YELLOW   = (255, 255,   0)
ORANGE   = (255, 127,   0)
PINK     = (255,   0, 255)
TURQUOISE= ( 64, 224, 208)

EMPT = BLACK 
WALL = BLUE
COIN = SALMON
PLET = TURQUOISE
GATE = PINK
PLAY = YELLOW

class Tile(IntEnum):
    WALL  = 0
    COIN  = 1
    POWER = 2
    EMPTY = 3
    GATE  = 4

class TileMap:
    def __init__(self,tiles):
        self.tiles = tiles

    def get_tile(self, x, y):
        return self.tiles[x][y]

    def is_wall(self, x, y):
        return self.tiles[x][y] == Tile.WALL

    def eat_coin(self, x, y):

        if self.tiles[x][y] == Tile.COIN:
            self.tiles[x][y] = Tile.EMPTY
            return True

        return False

TILES = [
        [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL],
        [WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL],
        [WALL, PLET, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, PLET, WALL],
        [WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL],
        [WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL],
        [WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL],
        [WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL],
        [WALL, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, WALL, WALL, GATE, GATE, WALL, WALL, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, COIN, EMPT, EMPT, EMPT, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, EMPT, EMPT, EMPT, COIN, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL],
        [WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL],
        [WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL],
        [WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL],
        [WALL, PLET, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, PLAY, PLAY, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, PLET, WALL],
        [WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL],
        [WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL],
        [WALL, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, WALL],
        [WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL],
        [WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL],
        [WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL],
        [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
        ]

def draw(win,tiles):
    win.fill(BLACK)
    x = 0
    y = 0
    gap = TEMP_WIDTH// M_HEIGHT
    for row in tiles:
        for tile in row:
            pygame.draw.rect(win, tile, (y* gap, x* gap, TILE_WIDTH, TILE_WIDTH))
            y += 1
        x += 1
        y = 0

    pygame.time.delay(10)
    pygame.display.update()

def main(win):
    run= True
    game_map = TileMap(TILES)

    while run:
        draw(win,game_map.tiles)
        for event in pygame.event.get():
            # Program Kill Switch
            if (event.type == pygame.QUIT):
                run= False
            

main(WIN)
