import pygame
from enum import Enum

#Tiles not pixels
M_WIDTH = 28
M_HEIGHT = 31
TEMP_WIDTH = 800
TILE_WIDTH = 124
WIN = pygame.display.set_mode((TEMP_WIDTH,TEMP_WIDTH))
pygame.display.set_caption("packer test 1")

BLUE     = (  0,   0, 255)
BLACK    = (  0,   0,   0)
SALMON   = (250, 128, 114)
YELLOW   = (255, 255,   0)
ORANGE   = (255, 127,   0)
PINK     = (255,   0, 255)
TURQUOISE= ( 64, 224, 208)

EMPT = BLACK 
WALL = BLUE
COIN = SALMON
PLET = TURQUOISE
GATE = PINK
PLAY = YELLOW

tiles= (
        (WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL),
        (WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL),
        (WALL, PLET, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, PLET, WALL),
        (WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL),
        (WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL),
        (WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL),
        (WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL),
        (WALL, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, WALL, WALL, GATE, GATE, WALL, WALL, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, COIN, EMPT, EMPT, EMPT, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, EMPT, EMPT, EMPT, COIN, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, EMPT, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPT, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL),
        (WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL),
        (WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL),
        (WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, WALL, WALL, COIN, WALL),
        (WALL, PLET, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, PLAY, PLAY, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, PLET, WALL),
        (WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL),
        (WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL),
        (WALL, COIN, COIN, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, WALL, WALL, COIN, COIN, COIN, COIN, COIN, COIN, WALL),
        (WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL),
        (WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL, WALL, COIN, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, COIN, WALL),
        (WALL, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, COIN, WALL),
        (WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL),
    )

def draw(win):
    win.fill(BLACK)
    x = 0
    y = 0
    gap = TEMP_WIDTH// M_HEIGHT
    for row in tiles:
        for tile in row:
            pygame.draw.rect(win, tile, (y* gap, x* gap, TILE_WIDTH, TILE_WIDTH))
            y += 1
        x += 1
        y = 0

    pygame.time.delay(10)
    pygame.display.update()

def main(win, width):
    run= True
    
    while run:
        draw(win)
        for event in pygame.event.get():
            # Program Kill Switch
            if (event.type == pygame.QUIT):
                run= False
            
main(WIN, TEMP_WIDTH)